# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
services:
  elevator:
    build: .
    command: ["uvicorn", "--factory", "elevate_manager.main:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      FASTRAMQPI__LOG_LEVEL: "INFO"
      FASTRAMQPI__JSON_LOGS: False

      FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker:5672/"
      FASTRAMQPI__MO_URL: "http://mo:5000"
      FASTRAMQPI__AUTH_SERVER: "http://keycloak:8080/auth"
      FASTRAMQPI__CLIENT_ID: "dipex"
      FASTRAMQPI__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
    networks:
      - os2mo_default
    volumes:
      - ./elevate_manager:/app/elevate_manager/:ro
      - ./tests/:/app/tests/:ro
    ports:
      - "127.0.0.1:8100:8000"

networks:
  os2mo_default:
    external: true
